# https://github.com/actions/checkout
# https://docs.github.com/actions/using-workflows

name: 'make test'

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Testing
      run: make test

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Testing
      run: make test
